### ISSUE TITLE
Gmail password refresh

### ISSUE THREAD

**Issue by abhinav1630** [prash29/VaccineNotifier#1]
Hi. I feel the password of the gmail smtp client gets expired after sometime. I think in this case, we need to update the password every time. Is there a possibility wherein we can auto-refresh it?

**Comment by prash29** [comment]
Hi,

I've not faced this issue. I have 2FA on my Gmail account. So, I created an app password using this link: https://support.google.com/accounts/answer/185833?p=InvalidSecondFactor&visit_id=637554658548216477-2576856839&rd=1

I've not faced any issues with the app password expiring. I've been using it for quite some time now and it's been okay
